PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS state(key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS buy_reviews(symbol TEXT NOT NULL, as_of TEXT NOT NULL,
 at TEXT NOT NULL, input_sha256 TEXT NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(symbol,as_of));
CREATE TABLE IF NOT EXISTS configs(id INTEGER PRIMARY KEY AUTOINCREMENT, at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS instruments(symbol TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS quotes(id INTEGER PRIMARY KEY AUTOINCREMENT, symbol TEXT NOT NULL, at TEXT NOT NULL,
 source TEXT NOT NULL, volume INTEGER NOT NULL, payload TEXT NOT NULL, UNIQUE(symbol,at,source));
CREATE INDEX IF NOT EXISTS quotes_symbol ON quotes(symbol,at DESC,id DESC);
CREATE TABLE IF NOT EXISTS bars(symbol TEXT NOT NULL, adjustment TEXT NOT NULL, day TEXT NOT NULL,
 payload TEXT NOT NULL, source TEXT NOT NULL, fetched_at TEXT NOT NULL, PRIMARY KEY(symbol,adjustment,day));
CREATE TABLE IF NOT EXISTS plans(id INTEGER PRIMARY KEY AUTOINCREMENT, as_of TEXT NOT NULL, execute_day TEXT NOT NULL,
 config_id INTEGER NOT NULL, at TEXT NOT NULL, payload TEXT NOT NULL, UNIQUE(as_of,config_id));
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT UNIQUE NOT NULL,
 symbol TEXT NOT NULL, side TEXT NOT NULL CHECK(side IN ('BUY','SELL')), quantity INTEGER NOT NULL CHECK(quantity>0),
 filled INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'pending', reason TEXT NOT NULL,
 kind TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, config_id INTEGER NOT NULL,
 last_quote_id INTEGER NOT NULL DEFAULT 0, blocked_reason TEXT NOT NULL DEFAULT '', plan_id INTEGER,
 FOREIGN KEY(config_id) REFERENCES configs(id));
CREATE TABLE IF NOT EXISTS fills(id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL, quote_id INTEGER NOT NULL,
 symbol TEXT NOT NULL, side TEXT NOT NULL, quantity INTEGER NOT NULL, price INTEGER NOT NULL,
 gross INTEGER NOT NULL, fee INTEGER NOT NULL, realized INTEGER NOT NULL DEFAULT 0, at TEXT NOT NULL,
 UNIQUE(order_id,quote_id), FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS cash_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT UNIQUE NOT NULL,
 delta INTEGER NOT NULL, kind TEXT NOT NULL, at TEXT NOT NULL, reference TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS lots(id INTEGER PRIMARY KEY AUTOINCREMENT, symbol TEXT NOT NULL,
 acquired_day TEXT NOT NULL, available_day TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>=0),
 cost INTEGER NOT NULL CHECK(cost>=0), risk_cost INTEGER NOT NULL CHECK(risk_cost>=0),
 high INTEGER NOT NULL CHECK(high>=0), fill_id INTEGER NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS position_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT NOT NULL UNIQUE,
 symbol TEXT NOT NULL, delta INTEGER NOT NULL, at TEXT NOT NULL, kind TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS liquidity(quote_id INTEGER PRIMARY KEY, consumed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS risk_intents(symbol TEXT PRIMARY KEY, reason TEXT NOT NULL, at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cooldown(symbol TEXT NOT NULL, day TEXT NOT NULL, PRIMARY KEY(symbol,day));
CREATE TABLE IF NOT EXISTS actions(id TEXT PRIMARY KEY, symbol TEXT NOT NULL, kind TEXT NOT NULL,
 record_day TEXT NOT NULL, ex_day TEXT NOT NULL, pay_day TEXT NOT NULL, value TEXT NOT NULL,
 verified INTEGER NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending',
 entitlement INTEGER NOT NULL DEFAULT 0, receivable INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS equity(at TEXT PRIMARY KEY, day TEXT NOT NULL, cash INTEGER NOT NULL,
 market_value INTEGER NOT NULL, receivable INTEGER NOT NULL, nav INTEGER NOT NULL, stale INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS runs(id INTEGER PRIMARY KEY AUTOINCREMENT, task TEXT NOT NULL, at TEXT NOT NULL,
 status TEXT NOT NULL, detail TEXT NOT NULL, duration REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS slots(key TEXT PRIMARY KEY, at TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS login_attempts(peer TEXT NOT NULL, at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS leases(key TEXT PRIMARY KEY, owner TEXT NOT NULL, expires REAL NOT NULL);
CREATE TABLE IF NOT EXISTS plan_inputs(plan_id INTEGER PRIMARY KEY, compressed BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS intraday_decisions(order_id INTEGER PRIMARY KEY, at TEXT NOT NULL,
 config_id INTEGER NOT NULL, payload TEXT NOT NULL, FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS t_cycles(id INTEGER PRIMARY KEY AUTOINCREMENT, day TEXT NOT NULL,
 symbol TEXT NOT NULL, config_id INTEGER NOT NULL, sell_order_id INTEGER NOT NULL UNIQUE,
 buy_order_id INTEGER UNIQUE, status TEXT NOT NULL, at TEXT NOT NULL, updated_at TEXT NOT NULL,
 FOREIGN KEY(sell_order_id) REFERENCES orders(id), FOREIGN KEY(buy_order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS t_cycle_buys(cycle_id INTEGER NOT NULL, order_id INTEGER NOT NULL UNIQUE,
 PRIMARY KEY(cycle_id,order_id), FOREIGN KEY(cycle_id) REFERENCES t_cycles(id), FOREIGN KEY(order_id) REFERENCES orders(id));
INSERT OR IGNORE INTO t_cycle_buys SELECT id,buy_order_id FROM t_cycles WHERE buy_order_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS notification_deliveries(id INTEGER PRIMARY KEY AUTOINCREMENT,
 event_key TEXT NOT NULL UNIQUE, channel TEXT NOT NULL, config_version INTEGER NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('trade','test')), fill_ids TEXT NOT NULL, message TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sending','sent','failed','cancelled','unknown')),
 at TEXT NOT NULL, updated_at TEXT NOT NULL, expires_at TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS notifications_pending ON notification_deliveries(channel,status,id);
CREATE TRIGGER IF NOT EXISTS fills_immutable_update BEFORE UPDATE ON fills BEGIN SELECT RAISE(ABORT,'immutable fills'); END;
CREATE TRIGGER IF NOT EXISTS fills_immutable_delete BEFORE DELETE ON fills BEGIN SELECT RAISE(ABORT,'immutable fills'); END;
CREATE TRIGGER IF NOT EXISTS cash_immutable_update BEFORE UPDATE ON cash_ledger BEGIN SELECT RAISE(ABORT,'immutable cash'); END;
CREATE TRIGGER IF NOT EXISTS cash_immutable_delete BEFORE DELETE ON cash_ledger BEGIN SELECT RAISE(ABORT,'immutable cash'); END;
CREATE TRIGGER IF NOT EXISTS position_immutable_update BEFORE UPDATE ON position_ledger BEGIN SELECT RAISE(ABORT,'immutable positions'); END;
CREATE TRIGGER IF NOT EXISTS position_immutable_delete BEFORE DELETE ON position_ledger BEGIN SELECT RAISE(ABORT,'immutable positions'); END;
PRAGMA user_version=1;
CREATE TABLE IF NOT EXISTS intraday_snapshots (
    symbol TEXT PRIMARY KEY,
    at TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS intraday_snapshot_loads (
    symbol TEXT NOT NULL,
    phase TEXT NOT NULL,
    at TEXT NOT NULL,
    error TEXT NOT NULL,
    PRIMARY KEY(symbol, phase)
);
CREATE TABLE IF NOT EXISTS minute_bars (
    symbol TEXT NOT NULL, at TEXT NOT NULL, source TEXT NOT NULL,
    fetched_at TEXT NOT NULL, payload TEXT NOT NULL,
    PRIMARY KEY(symbol, at, source)
);
